---
########################
# Maximal Setting File #
########################

## Quick settings feature reference
# elements ending in _path are resolved from the directory of this settings file
# string elements can be templated into children using {{ELEMENT}}
# any element defined at the top level will be available to all "product/section" unless overridden


project: SW_PLL
version: 2.0.0

products:
  SW_PLL:
    documentation:
      build_path: ./_build
      output_path: ./_out

documentation:
  title: Maximal Demo Project
  root_doc: index.rst
  exclude_patterns_path: ./exclude-patterns.inc
  substitutions_path: ./substitutions.inc
  linkcheck_ignore_regex: [".*xmos-broken-link.*"]
  doc_dirname: rst
  build_path: ./_build
  output_path: ./_out
  doxygen_dirname: _doxygen
  // doctrees_dirname: _doctrees
  doctrees_dirname: _doctrees
  autosection_label_depth: 3
  latex_toc_depth: 3
  enable_latex_index: false
  doxygen_projects:
    SW_PLL:
      doxyfile_path: ./Doxyfile.inc
      doxy_overrides: |
        GENERATE_HTML = yes
        GENERATE_LATEX = yes

  pdfs:
    index:
      pdf_title: '{{product}} Programming Guide \newline'
      pdf_filename: '{{product}}_progamming_guide_v{{version}}'

